version: 2
updates:
  - package-ecosystem: pip
    directory: "/requirements"
    schedule:
      interval: "cron"
      cronjob: "0 6 5 */3 *"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "cron"
      cronjob: "0 6 5 */3 *"
